sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t elendil910/docker-react -f Dockerfie.dev .

script:
    - docker run -e CI=true elendil910/docker-react npm run test
 